### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bradh**
Make patent non-licensing explicit.

### CODE REVIEW

**Comment by adamjw24** [comment]
Thanks for this proposal. Every wording regarding to the license has to be signed of by way more people than functional changes, so the consideration of this might take some time.

The information is contained in the license file, so I guess it's not a time critical change, but rather a small connivance.

**Comment by bradh** [comment]
Would it be easier if it used the exact wording from the license file?
```
No patent rights, trademark rights and/or 
other Intellectual Property Rights other than the copyrights concerning 
the Software are granted under this license.
```
?

**Comment by adamjw24** [comment]
I'll know in a week at earliest, bcs of vacation and stuff.

Myself, I don't see a point bringing up specific parts of the license for people who don't want to click the link. I looked at that part of the readme, and it doesn't say anything about the license, it just states the copyright and says too look up the license file. If there were other points being discussed in the readme I'd be more agreeable, but the readme doesnt say "in short, the license is..., and for details look up the actual license", it just says "go look up the actual license". If we start doing excerpts of the license, it becomes a whole new discussion, what points should be contained within the excerpt, and what legal meaning does the excerpt have and so on. Do you see the point?

I think the license itself is straightforward enough as it is, and it is what it is. We'll discuss it eventally tho.

**Comment by bradh** [comment]
I think this case is a bit different. Most projects disclaim patent licences,  but actually having a patent pool organised is rare.

**Comment by adamjw24** [comment]
I had a look at x265 and aomenc and neither mentions patent situation in the readme. I really don't think this is the single most important aspect of the license to be mentioned.

**Pull request closed without merging**
