### PR TITLE
Add AArch64 Neon implementation of motionErrorLumaInt8

### PR DESCRIPTION
**Pull request by georges-arm**
Add a new Neon implementation for the MCTF `motionErrorLumaInt8` kernel, performing a sum of squared difference calculation with early-exit.

Running a video encoding job on a Neoverse V2 machine using the `--preset=fast` setting shows a ~0.5% improvement in reported FPS.

### CODE REVIEW

**Comment by adamjw24** [comment]
Just as a side note. We are planing a release code freeze by the end of the month for a release by the end of the year.

Do you have anything you want to make it before that? Anything we should possibly wait for?

**Comment by georges-arm** [comment]
> Just as a side note. We are planing a release code freeze by the end of the month for a release by the end of the year.
> 
> Do you have anything you want to make it in before that? Anything we should possibly wait for?

Thanks for the heads up. I am currently finishing off the first SVE code patch which would be nice to get in since that gives a good improvement and motivates the earlier addition of the SVE CMake flag. Everything else can probably wait for a future release.

**Comment by adamjw24** [comment]
We are starting the testing for a new version and the deadline for any contributions is this Friday afternoon Berlin time.

**Comment by georges-arm** [comment]
> We are starting the testing for a new version and the deadline for any contributions is this Friday afternoon Berlin time.

Thanks for the reminder, I've put up a first SVE patch and the required associated CMake changes in #474.

**Pull request merged**
